apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-devops-deployment
  labels:
    app: flask-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-devops-app
  template:
    metadata:
      labels:
        app: flask-devops-app
    spec:
      containers:
      - name: flask-devops-container
        image: 904233103745.dkr.ecr.us-east-1.amazonaws.com/flask-devops-app:latest   # replace with your ECR repo URI
        ports:
        - containerPort: 5000
