apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-devops-deployment
  labels:
    app: flask-devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-devops-app
  template:
    metadata:
      labels:
        app: flask-devops-app
    spec:
      containers:
      - name: flask-devops-container
        image: <your-ecr-repo-uri>:latest   # replace with your ECR repo URI
        ports:
        - containerPort: 5000
