apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-devops-app   # 🔥 must match Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
