name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker Image
        run: docker build -t flask-devops-app ./app

      # Step 4: Run container (just to test it works)
      - name: Run container
        run: docker run -d -p 5000:5000 flask-devops-app
